CHARACTER_WIDTH = 20
CHARACTER_HEIGHT = 20
CHARACTER_SPRITE_WIDTH = 32
CHARACTER_SPRITE_HEIGHT = 32
CHARACTER_SPEED = 6
CHARACTER_JUMP_FRAMES = 8

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 640
FLOOR_Y = 300

ARROW_MAX_SPEED = 12
FPS = 60
